// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OneShelf.Videos.Database;

#nullable disable

namespace OneShelf.Videos.Database.Migrations.VideosDatabaseMigrations
{
    [DbContext(typeof(VideosDatabase))]
    [Migration("20240928132621_Media10")]
    partial class Media10
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OneShelf.Videos.Database.Models.Album", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Albums");
                });

            modelBuilder.Entity("OneShelf.Videos.Database.Models.AlbumConstraint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("After")
                        .HasColumnType("datetime2");

                    b.Property<int>("AlbumId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Before")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Include")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSquare")
                        .HasColumnType("bit");

                    b.Property<string>("StaticMessageSelectedType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StaticTopicId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.ToTable("AlbumConstraints");
                });

            modelBuilder.Entity("OneShelf.Videos.Database.Models.InventoryItem", b =>
                {
                    b.Property<int>("DatabaseInventoryItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DatabaseInventoryItemId"));

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContributorInfoDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContributorInfoProfilePictureBaseUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPhoto")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVideo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("MediaMetadataCreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("MediaMetadataHeight")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("MediaMetadataPhotoApertureFNumber")
                        .HasColumnType("real");

                    b.Property<string>("MediaMetadataPhotoCameraMake")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MediaMetadataPhotoCameraModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MediaMetadataPhotoExposureTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("MediaMetadataPhotoFocalLength")
                        .HasColumnType("real");

                    b.Property<int?>("MediaMetadataPhotoIsoEquivalent")
                        .HasColumnType("int");

                    b.Property<string>("MediaMetadataVideoCameraMake")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MediaMetadataVideoCameraModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("MediaMetadataVideoFps")
                        .HasColumnType("float");

                    b.Property<string>("MediaMetadataVideoStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MediaMetadataWidth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SyncDate")
                        .HasColumnType("datetime2");

                    b.HasKey("DatabaseInventoryItemId");

                    b.ToTable("InventoryItems");
                });

            modelBuilder.Entity("OneShelf.Videos.Database.Models.Live.LiveChat", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LiveChats");
                });

            modelBuilder.Entity("OneShelf.Videos.Database.Models.Live.LiveDownloadedItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("LiveMediaMediaId")
                        .HasColumnType("bigint");

                    b.Property<string>("ThumbnailFileName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FileName")
                        .IsUnique();

                    b.HasIndex("LiveMediaMediaId")
                        .IsUnique();

                    b.ToTable("LiveDownloadedItems");
                });

            modelBuilder.Entity("OneShelf.Videos.Database.Models.Live.LiveMedia", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<long>("LiveTopicLiveChatId")
                        .HasColumnType("bigint");

                    b.Property<string>("DocumentAttributeTypes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentAttributes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Duration")
                        .HasColumnType("float");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Flags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<bool>("IsForwarded")
                        .HasColumnType("bit");

                    b.Property<int>("LiveTopicId")
                        .HasColumnType("int");

                    b.Property<DateTime>("MediaDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MediaFlags")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("MediaId")
                        .HasColumnType("bigint");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("MessageDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MimeType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SelectedType")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("nvarchar(max)")
                        .HasComputedColumnSql("\r\ncase \r\nwhen type = 'Photo' then 'Photo' \r\nwhen MimeType like 'video/%' then 'Video' \r\nwhen mimetype = 'image/webp' then null \r\nwhen mimetype = 'application/x-tgsticker' then null\r\nwhen MimeType like 'image/%' then 'Photo' \r\nelse null\r\nend\r\n");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VideoFlags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id", "LiveTopicLiveChatId");

                    b.HasIndex("LiveTopicId", "LiveTopicLiveChatId");

                    b.ToTable("LiveMediae");
                });

            modelBuilder.Entity("OneShelf.Videos.Database.Models.Live.LiveTopic", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<long>("LiveChatId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id", "LiveChatId");

                    b.HasIndex("LiveChatId");

                    b.ToTable("LiveTopics");
                });

            modelBuilder.Entity("OneShelf.Videos.Database.Models.Media", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long?>("LiveChatId")
                        .HasColumnType("bigint");

                    b.Property<int?>("LiveMediaId")
                        .HasColumnType("int");

                    b.Property<long?>("StaticChatId")
                        .HasColumnType("bigint");

                    b.Property<int?>("StaticMessageId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LiveChatId");

                    b.HasIndex("LiveMediaId", "LiveChatId")
                        .IsUnique()
                        .HasFilter("[LiveMediaId] IS NOT NULL AND [LiveChatId] IS NOT NULL");

                    b.HasIndex("StaticChatId", "StaticMessageId")
                        .IsUnique()
                        .HasFilter("[StaticChatId] IS NOT NULL AND [StaticMessageId] IS NOT NULL");

                    b.ToTable("Mediae");
                });

            modelBuilder.Entity("OneShelf.Videos.Database.Models.Static.StaticChat", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StaticChatFolderId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("StaticChatFolderId")
                        .IsUnique();

                    b.ToTable("StaticChats");
                });

            modelBuilder.Entity("OneShelf.Videos.Database.Models.Static.StaticChatFolder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Root")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("StaticChatFolders");
                });

            modelBuilder.Entity("OneShelf.Videos.Database.Models.Static.StaticMessage", b =>
                {
                    b.Property<long>("StaticChatId")
                        .HasColumnType("bigint");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Action")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Actor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ActorId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Boosts")
                        .HasColumnType("int");

                    b.Property<string>("ContactInformation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("DateUnixtime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Duration")
                        .HasColumnType("int");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("int");

                    b.Property<DateTime>("Edited")
                        .HasColumnType("datetime2");

                    b.Property<string>("EditedUnixtime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("File")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ForwardedFrom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("From")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FromId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Height")
                        .HasColumnType("int");

                    b.Property<string>("InlineBotButtons")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inviter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LiveLocationPeriodSeconds")
                        .HasColumnType("int");

                    b.Property<string>("LocationInformation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MediaType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Members")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MessageId")
                        .HasColumnType("int");

                    b.Property<string>("MimeType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("NewIconEmojiId")
                        .HasColumnType("bigint");

                    b.Property<string>("NewTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Performer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Poll")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReplyToMessageId")
                        .HasColumnType("int");

                    b.Property<string>("ReplyToPeerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SavedFrom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ScheduleDate")
                        .HasColumnType("int");

                    b.Property<string>("SelectedType")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("nvarchar(max)")
                        .HasComputedColumnSql("case when photo is not null then 'photo' when mimetype like 'video/%' and isnull(mediatype, 'null') in ('video_file', 'null') then 'video' else null end");

                    b.Property<int?>("StaticTopicRootMessageIdOr0")
                        .HasColumnType("int");

                    b.Property<string>("StickerEmoji")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TextEntities")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Thumbnail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ViaBot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Width")
                        .HasColumnType("int");

                    b.HasKey("StaticChatId", "Id");

                    b.HasIndex("StaticChatId", "StaticTopicRootMessageIdOr0");

                    b.ToTable("StaticMessages");
                });

            modelBuilder.Entity("OneShelf.Videos.Database.Models.Static.StaticTopic", b =>
                {
                    b.Property<long>("StaticChatId")
                        .HasColumnType("bigint");

                    b.Property<int>("RootMessageIdOr0")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("OriginalTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StaticChatId", "RootMessageIdOr0");

                    b.ToTable("StaticTopics");
                });

            modelBuilder.Entity("OneShelf.Videos.Database.Models.UploadedAlbum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlbumId")
                        .HasColumnType("int");

                    b.Property<string>("GoogleAlbumId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId")
                        .IsUnique();

                    b.ToTable("UploadedAlbums");
                });

            modelBuilder.Entity("OneShelf.Videos.Database.Models.UploadedItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FileNameTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MediaId")
                        .HasColumnType("int");

                    b.Property<string>("MediaItemId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("MediaItemIsPhoto")
                        .HasColumnType("bit");

                    b.Property<bool?>("MediaItemIsVideo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("MediaItemMetadataCreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("MediaItemMimeType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("MediaItemSyncDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusCode")
                        .HasColumnType("int");

                    b.Property<string>("StatusMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TelegramPublishedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MediaId")
                        .IsUnique();

                    b.ToTable("UploadedItems");
                });

            modelBuilder.Entity("OneShelf.Videos.Database.Models.AlbumConstraint", b =>
                {
                    b.HasOne("OneShelf.Videos.Database.Models.Album", "Album")
                        .WithMany("Constraints")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");
                });

            modelBuilder.Entity("OneShelf.Videos.Database.Models.Live.LiveMedia", b =>
                {
                    b.HasOne("OneShelf.Videos.Database.Models.Live.LiveTopic", "LiveTopic")
                        .WithMany("LiveMediae")
                        .HasForeignKey("LiveTopicId", "LiveTopicLiveChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LiveTopic");
                });

            modelBuilder.Entity("OneShelf.Videos.Database.Models.Live.LiveTopic", b =>
                {
                    b.HasOne("OneShelf.Videos.Database.Models.Live.LiveChat", "LiveChat")
                        .WithMany("LiveTopics")
                        .HasForeignKey("LiveChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LiveChat");
                });

            modelBuilder.Entity("OneShelf.Videos.Database.Models.Media", b =>
                {
                    b.HasOne("OneShelf.Videos.Database.Models.Live.LiveChat", "LiveChat")
                        .WithMany("Mediae")
                        .HasForeignKey("LiveChatId");

                    b.HasOne("OneShelf.Videos.Database.Models.Static.StaticChat", "StaticChat")
                        .WithMany("Mediae")
                        .HasForeignKey("StaticChatId");

                    b.HasOne("OneShelf.Videos.Database.Models.Live.LiveMedia", "LiveMedia")
                        .WithOne("Media")
                        .HasForeignKey("OneShelf.Videos.Database.Models.Media", "LiveMediaId", "LiveChatId");

                    b.HasOne("OneShelf.Videos.Database.Models.Static.StaticMessage", "StaticMessage")
                        .WithOne("Media")
                        .HasForeignKey("OneShelf.Videos.Database.Models.Media", "StaticChatId", "StaticMessageId");

                    b.Navigation("LiveChat");

                    b.Navigation("LiveMedia");

                    b.Navigation("StaticChat");

                    b.Navigation("StaticMessage");
                });

            modelBuilder.Entity("OneShelf.Videos.Database.Models.Static.StaticChat", b =>
                {
                    b.HasOne("OneShelf.Videos.Database.Models.Static.StaticChatFolder", "StaticChatFolder")
                        .WithOne("StaticChat")
                        .HasForeignKey("OneShelf.Videos.Database.Models.Static.StaticChat", "StaticChatFolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StaticChatFolder");
                });

            modelBuilder.Entity("OneShelf.Videos.Database.Models.Static.StaticMessage", b =>
                {
                    b.HasOne("OneShelf.Videos.Database.Models.Static.StaticChat", "StaticChat")
                        .WithMany("Messages")
                        .HasForeignKey("StaticChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OneShelf.Videos.Database.Models.Static.StaticTopic", "StaticTopic")
                        .WithMany("StaticMessages")
                        .HasForeignKey("StaticChatId", "StaticTopicRootMessageIdOr0");

                    b.Navigation("StaticChat");

                    b.Navigation("StaticTopic");
                });

            modelBuilder.Entity("OneShelf.Videos.Database.Models.Static.StaticTopic", b =>
                {
                    b.HasOne("OneShelf.Videos.Database.Models.Static.StaticChat", "StaticChat")
                        .WithMany()
                        .HasForeignKey("StaticChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StaticChat");
                });

            modelBuilder.Entity("OneShelf.Videos.Database.Models.UploadedAlbum", b =>
                {
                    b.HasOne("OneShelf.Videos.Database.Models.Album", "Album")
                        .WithOne("UploadedAlbum")
                        .HasForeignKey("OneShelf.Videos.Database.Models.UploadedAlbum", "AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");
                });

            modelBuilder.Entity("OneShelf.Videos.Database.Models.UploadedItem", b =>
                {
                    b.HasOne("OneShelf.Videos.Database.Models.Media", "Media")
                        .WithOne("UploadedItem")
                        .HasForeignKey("OneShelf.Videos.Database.Models.UploadedItem", "MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Media");
                });

            modelBuilder.Entity("OneShelf.Videos.Database.Models.Album", b =>
                {
                    b.Navigation("Constraints");

                    b.Navigation("UploadedAlbum");
                });

            modelBuilder.Entity("OneShelf.Videos.Database.Models.Live.LiveChat", b =>
                {
                    b.Navigation("LiveTopics");

                    b.Navigation("Mediae");
                });

            modelBuilder.Entity("OneShelf.Videos.Database.Models.Live.LiveMedia", b =>
                {
                    b.Navigation("Media");
                });

            modelBuilder.Entity("OneShelf.Videos.Database.Models.Live.LiveTopic", b =>
                {
                    b.Navigation("LiveMediae");
                });

            modelBuilder.Entity("OneShelf.Videos.Database.Models.Media", b =>
                {
                    b.Navigation("UploadedItem");
                });

            modelBuilder.Entity("OneShelf.Videos.Database.Models.Static.StaticChat", b =>
                {
                    b.Navigation("Mediae");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("OneShelf.Videos.Database.Models.Static.StaticChatFolder", b =>
                {
                    b.Navigation("StaticChat");
                });

            modelBuilder.Entity("OneShelf.Videos.Database.Models.Static.StaticMessage", b =>
                {
                    b.Navigation("Media");
                });

            modelBuilder.Entity("OneShelf.Videos.Database.Models.Static.StaticTopic", b =>
                {
                    b.Navigation("StaticMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
