// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OneShelf.Videos.App.Database;

#nullable disable

namespace OneShelf.Videos.App.Migrations.VideosDatabaseMigrations
{
    [DbContext(typeof(VideosDatabase))]
    [Migration("20240824052457_InventoryItems")]
    partial class InventoryItems
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OneShelf.Videos.App.Database.Models.ChatFolder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Root")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ChatFolders");
                });

            modelBuilder.Entity("OneShelf.Videos.App.Database.Models.InventoryItem", b =>
                {
                    b.Property<int>("DatabaseInventoryItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DatabaseInventoryItemId"));

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContributorInfoDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContributorInfoProfilePictureBaseUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPhoto")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVideo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("MediaMetadataCreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("MediaMetadataHeight")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("MediaMetadataPhotoApertureFNumber")
                        .HasColumnType("real");

                    b.Property<string>("MediaMetadataPhotoCameraMake")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MediaMetadataPhotoCameraModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MediaMetadataPhotoExposureTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("MediaMetadataPhotoFocalLength")
                        .HasColumnType("real");

                    b.Property<int?>("MediaMetadataPhotoIsoEquivalent")
                        .HasColumnType("int");

                    b.Property<string>("MediaMetadataVideoCameraMake")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MediaMetadataVideoCameraModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("MediaMetadataVideoFps")
                        .HasColumnType("float");

                    b.Property<string>("MediaMetadataVideoStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MediaMetadataWidth")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SyncDate")
                        .HasColumnType("datetime2");

                    b.HasKey("DatabaseInventoryItemId");

                    b.ToTable("InventoryItems");
                });

            modelBuilder.Entity("OneShelf.Videos.App.Database.Models.Json.Chat", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int>("ChatFolderId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ChatFolderId")
                        .IsUnique();

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("OneShelf.Videos.App.Database.Models.Json.Message", b =>
                {
                    b.Property<int>("DatabaseMessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DatabaseMessageId"));

                    b.Property<string>("Action")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Actor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ActorId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Boosts")
                        .HasColumnType("int");

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint");

                    b.Property<string>("ContactInformation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("DateUnixtime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Duration")
                        .HasColumnType("int");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("int");

                    b.Property<DateTime>("Edited")
                        .HasColumnType("datetime2");

                    b.Property<string>("EditedUnixtime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("File")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ForwardedFrom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("From")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FromId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Height")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("InlineBotButtons")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inviter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LiveLocationPeriodSeconds")
                        .HasColumnType("int");

                    b.Property<string>("LocationInformation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MediaType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Members")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MessageId")
                        .HasColumnType("int");

                    b.Property<string>("MimeType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("NewIconEmojiId")
                        .HasColumnType("bigint");

                    b.Property<string>("NewTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Performer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Poll")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReplyToMessageId")
                        .HasColumnType("int");

                    b.Property<string>("ReplyToPeerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SavedFrom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ScheduleDate")
                        .HasColumnType("int");

                    b.Property<string>("StickerEmoji")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TextEntities")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Thumbnail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ViaBot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Width")
                        .HasColumnType("int");

                    b.HasKey("DatabaseMessageId");

                    b.HasIndex("ChatId", "Id")
                        .IsUnique();

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("OneShelf.Videos.App.Database.Models.UploadedItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FileNameTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MediaItemId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("MediaItemIsPhoto")
                        .HasColumnType("bit");

                    b.Property<bool?>("MediaItemIsVideo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("MediaItemMetadataCreationType")
                        .HasColumnType("datetime2");

                    b.Property<string>("MediaItemMimeType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("MediaItemSyncDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MessageId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusCode")
                        .HasColumnType("int");

                    b.Property<string>("StatusMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TelegramPublishedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("UploadedItems");
                });

            modelBuilder.Entity("OneShelf.Videos.App.Database.Models.Json.Chat", b =>
                {
                    b.HasOne("OneShelf.Videos.App.Database.Models.ChatFolder", "ChatFolder")
                        .WithOne("Chat")
                        .HasForeignKey("OneShelf.Videos.App.Database.Models.Json.Chat", "ChatFolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatFolder");
                });

            modelBuilder.Entity("OneShelf.Videos.App.Database.Models.Json.Message", b =>
                {
                    b.HasOne("OneShelf.Videos.App.Database.Models.Json.Chat", "Chat")
                        .WithMany("Messages")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");
                });

            modelBuilder.Entity("OneShelf.Videos.App.Database.Models.ChatFolder", b =>
                {
                    b.Navigation("Chat");
                });

            modelBuilder.Entity("OneShelf.Videos.App.Database.Models.Json.Chat", b =>
                {
                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
