// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OneShelf.Videos.App.Database;

#nullable disable

namespace OneShelf.Videos.App.Migrations
{
    [DbContext(typeof(VideosDatabase))]
    [Migration("20240822032311_FileNameTimestamps")]
    partial class FileNameTimestamps
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("OneShelf.Videos.App.Database.Models.UploadedItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ChatId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FileNameTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MediaItemId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("MediaItemIsPhoto")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("MediaItemIsVideo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("MediaItemMetadataCreationType")
                        .HasColumnType("TEXT");

                    b.Property<string>("MediaItemMimeType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("MediaItemSyncDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("MessageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<int>("StatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StatusMessage")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TelegramPublishedOn")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UploadedItems");
                });
#pragma warning restore 612, 618
        }
    }
}
