# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET frontend publish

permissions:
  contents: write

on:
# Triggers the workflow on push or pull request events but only for the master branch
  #push:
    #branches: [ master ]
# Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:
  push:
    tags:
      - "fv*"

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
#    - name: Wasm tools
#      run: dotnet workload install wasm-tools
    - name: Restore dependencies
      run: dotnet restore OneShelf.Frontend/OneShelf.Frontend.Web/OneShelf.Frontend.Web.csproj
    - name: Build
      run: dotnet build OneShelf.Frontend/OneShelf.Frontend.Web/OneShelf.Frontend.Web.csproj --no-restore --configuration Release
    - name: Publish 1
      run: dotnet publish OneShelf.Frontend/OneShelf.Frontend.Web/OneShelf.Frontend.Web.csproj --no-restore --configuration Release
      
    - run: Compress-Archive -Path OneShelf.Frontend/OneShelf.Frontend.Web/bin/Release/net8.0/publish/* -Destination OneShelf.Frontend.Web.zip
  
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: true
        files: |
          LICENSE
          OneShelf.Frontend.Web.zip