# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: playground

permissions:
  contents: write

on:
# Triggers the workflow on push or pull request events but only for the master branch
  #push:
    #branches: [ master ]
# Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:
  push:
    tags:
      - "v*-p"

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

    - name: Replace 1
      uses: richardrigutins/replace-in-files@v2
      with:
        files: 'HarmonyDB.Playground/HarmonyDB.Playground.Web/Views/Shared/_Layout.cshtml'
        search-text: '{#version#}'
        replacement-text: "${{ github.ref_name }}-${{ steps.date.outputs.date }}"

    - name: Restore dependencies
      run: dotnet restore HarmonyDB.Playground/HarmonyDB.Playground.Web/HarmonyDB.Playground.Web.csproj
    - name: Build
      run: dotnet build HarmonyDB.Playground/HarmonyDB.Playground.Web/HarmonyDB.Playground.Web.csproj --no-restore --configuration Release
    - name: Publish 1
      run: dotnet publish HarmonyDB.Playground/HarmonyDB.Playground.Web/HarmonyDB.Playground.Web.csproj --no-restore

    - run: Compress-Archive -Path HarmonyDB.Playground/HarmonyDB.Playground.Web/bin/Release/net8.0/publish/* -Destination HarmonyDB.Playground.Web.zip
  
#    - name: Test
#      run: dotnet test --no-build --verbosity normal
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: true
        files: |
          LICENSE
          *.zip